apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 5
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: mespinosaz/hello-random-string:2
        name: main2
        ports:
          - containerPort: 9090
