apiVersion: v1
kind: Pod
metadata:
    name: main
    labels:
      app: hello
spec:
    containers:
      - image: mespinosaz/hello-random-string
        name: main
        ports:
          - containerPort: 9090
